name: Android Build (Cloud AAB)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install SDKMAN and Gradle 8.7
      shell: bash
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.7
        gradle --version

    - name: Generate Gradle Wrapper (8.7)
      shell: bash
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        gradle wrapper --gradle-version 8.7

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build release AAB
      run: ./gradlew bundleRelease

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: pushupcards-aab
        path: app/build/outputs/bundle/release/*.aab
